# Generated by Django 5.0.3 on 2024-03-28 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscriptionchoices_monthly_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpaymentstatus',
            name='add_free_trial_days',
        ),
        migrations.RemoveField(
            model_name='userpaymentstatus',
            name='tier',
        ),
    ]
