# Generated by Django 5.0.3 on 2024-03-29 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_remove_userpaymentstatus_add_free_trial_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscriptions',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('paid', 'paid'), ('cancelled', 'cancelled')], max_length=300),
        ),
    ]
