# Generated by Django 5.0.3 on 2024-03-20 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPreferenceType',
        ),
    ]
