# Generated by Django 5.0.3 on 2024-03-31 17:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_ai_credits_remaining', models.IntegerField(default=5)),
                ('purchased_ai_credits_remaining', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HeadlineRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('unique_id', models.UUIDField(default=uuid.uuid4)),
                ('input_phrase', models.CharField(max_length=20000)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('response', models.TextField(blank=True, max_length=10000, null=True)),
                ('user_ai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ai.userai')),
            ],
        ),
    ]
