# Generated by Django 5.0.3 on 2024-03-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headlinerequest',
            name='tone',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='headlinerequest',
            name='input_phrase',
            field=models.TextField(max_length=20000),
        ),
    ]
