# Generated by Django 5.0.3 on 2024-03-27 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('free_tier', 'free_tier'), ('professional', 'professional'), ('business', 'business'), ('enterprise', 'enterprise')], max_length=200, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('tier_ranking', models.IntegerField(unique=True)),
                ('badge_color', models.CharField(blank=True, max_length=50, null=True)),
                ('workspaces', models.IntegerField(default=1)),
                ('roadmaps', models.IntegerField(default=1)),
                ('timelines', models.IntegerField(default=1)),
                ('monthly_ai_credits', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='UserTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tiers.tier')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
